### ISSUE TITLE
Document List | One item list issues

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/connect_vva#11]
# Description
When listing documents for certain file numbers, sometimes the `record[:fn_dcmnt_id]` is returning an array instead of a hash

## Reproduction Steps

**Scenario 1 -**

1. Go to eFolder prod
1. Find Download id 40649
1. Try to get VVA Document list
1. Fail
**Validated in the following Environment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Logs:

```
vva.document_list.get_by_claim_number("******")
TypeError: no implicit conversion of Symbol into Integer
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/bundler/gems/connect_vva-7d9f82dc9031/lib/vva/services/document_list.rb:23:in `[]'
        from /opt/efolder-express/src/vendor/bundle/ruby/2.3.0/bundler/gems/connect_vva-7d9f82dc9031/lib/vva/services/document_list.rb:23:in `block in get_by_claim_number'
```
https://github.com/department-of-veterans-affairs/connect_vva/blob/master/lib/vva/services/document_list.rb#L23

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/435/events/

**Comment by kierachell** [comment]
**PASSED**

VVA did not provide a test case for this.
