### ISSUE TITLE
[3] Connect VVA - Implement GetDocumentContent

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/connect_vva#2]
Tech Notes:
GetDocumentContent() accepts the `document id` and returns the actual document content from the Virtual VA image repository.  This call will only be used for retrieving non-restricted documents.

**Comment by kierachell** [comment]
```
params = {
        document_id: "{0E62D898-FE72-496F-91EF-3E5F202E7A26}",
        source: "P8",
        format: "PDF",
        jro: "459",
        ssn: "654654654"
}
```
Restricted document is raising a weird erro. What is this "objectStore" thing?
```
Savon::SOAPFault: (soap:Server) The requested item was not found. Object identity: classId=Document&objectId={E2A413C6-93D0-4E06-9FEA-3A0EB3EC2A1B}&objectStore={55545BC1-99EF-4C54-831C-D9D24CEF34E5}.  Class name: Document.
from /Users/vhaisavovka/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
```

**Comment by aroltsch** [comment]
Let's wait for test access

**Comment by kierachell** [comment]
```
D, [2017-05-24T11:00:43.516224 #9804] DEBUG -- : HTTPI POST request to vbaphi5topp.vba.va.gov (net_http)
I, [2017-05-24T11:00:44.169233 #9804]  INFO -- : SOAP response (status 500)
D, [2017-05-24T11:00:44.169522 #9804] DEBUG -- : <?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <soap:Fault>
      <faultcode>soap:Server</faultcode>
      <faultstring>The user is not authenticated.</faultstring>
      <detail>
        <ns1:VVAFault xmlns:ns1="http://service.bfi.va.gov/"/>
      </detail>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>

Savon::SOAPFault: (soap:Server) The user is not authenticated.
from /opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/savon-2.11.1/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'
```

**Comment by aroltsch** [comment]
This issue https://github.com/department-of-veterans-affairs/connect_vva/issues/2#issuecomment-303752355 should be resolved. @kierachell

**Comment by kierachell** [comment]
## A document _might_ be in the list, but VVA won't give it to you
```
document: {7D7EE7C9-B8C8-4282-B5D8-6ADBA5CFED94} didn't work; was it restricted? true
got error (soap:Server) The file does not exist /filenet/file_stores/TS_OBJSTORE1_FS18/content/FN7/FN1/FN{7D7EE7C9-B8C8-4282-B5D8-6ADBA5CFED94}{C7E8A04C-1A9E-4E1B-A14F-FD722C1FF146}-0.pdf.
```
- Not related to being restricted:
```
document: {7D7EE7C9-B8C8-4282-B5D8-6ADBA5CFED94}.PDF didn't work; was it restricted? true
got error (soap:Server) The file does not exist /filenet/file_stores/TS_OBJSTORE1_FS18/content/FN7/FN1/FN{7D7EE7C9-B8C8-4282-B5D8-6ADBA5CFED94}{C7E8A04C-1A9E-4E1B-A14F-FD722C1FF146}-0.pdf.
getting document {2435EDD4-D705-4514-9C0D-519A7FF3FD17}
document: {2435EDD4-D705-4514-9C0D-519A7FF3FD17}.TIFF downloaded; was it restricted? false
getting document {13FFC740-EE56-40C3-8287-2B91EA403858}
document: {13FFC740-EE56-40C3-8287-2B91EA403858}.PDF downloaded; was it restricted? true
```

**Comment by aroltsch** [comment]
I will be passing this info to the VVA dev team.

**Comment by kierachell** [comment]
### With clams 123123123
```
getting document {52EB085B-5BFE-4194-9A85-518F8FE8A114}
document: {52EB085B-5BFE-4194-9A85-518F8FE8A114}.TIFF for claim 123123123 didn't work; was it restricted? false; and type 344
got error (soap:Server) The file does not exist /filenet/file_stores/TS_OBJSTORE1_FS27/content/FN2/FN4/FN{52EB085B-5BFE-4194-9A85-518F8FE8A114}{367030C2-A05A-439F-A50F-C89C11494EC9}-0.
getting document {53C7229B-1CA9-4843-A9C3-227EAD4D5C88}
document: {53C7229B-1CA9-4843-A9C3-227EAD4D5C88}.PDF for claim 123123123 didn't work; was it restricted? false; and type 11
got error (soap:Server) The file does not exist /filenet/file_stores/TS_OBJSTORE1_FS24/content/FN12/FN7/FN{53C7229B-1CA9-4843-A9C3-227EAD4D5C88}{51ADA936-6C2E-4E02-99E6-E1021AAEB809}-0.
getting document {53E56963-2C59-48F8-AE68-05E361F617CF}
document: {53E56963-2C59-48F8-AE68-05E361F617CF}.PDF for claim 123123123 didn't work; was it restricted? false; and type 11
got error (soap:Server) The file does not exist /filenet/file_stores/TS_OBJSTORE1_FS26/content/FN13/FN16/FN{53E56963-2C59-48F8-AE68-05E361F617CF}{068448A9-317A-42B6-B91D-1839D6481640}-0.
getting document {1454F27D-31CB-4108-87B0-DFF3B2386691}
document: {1454F27D-31CB-4108-87B0-DFF3B2386691}.PDF for claim 123123123 didn't work; was it restricted? false; and type 11
got error (soap:Server) The file does not exist /filenet/file_stores/TS_OBJSTORE1_FS23/content/FN2/FN7/FN{1454F27D-31CB-4108-87B0-DFF3B2386691}{939F487A-526C-4913-A363-6D9149EC3AC0}-0.
getting document {28D53F63-E622-4B96-862D-8BE62B87C869}
document: {28D53F63-E622-4B96-862D-8BE62B87C869}.PDF downloaded; was it restricted? false; and type: 10
getting document {211333B0-99F6-459E-BBAD-6CE20FCF0052}
```

**Comment by kierachell** [comment]
Am I understanding the email correctly that they changed their data?

**Comment by aroltsch** [comment]
@kierachell yes, they have changed the data.

**Comment by kierachell** [comment]
**PASSED**

Based on emails with VVA - their test data is dirty, but after some cleanup:
```
document: {CE7EA941-7CB8-4627-8788-E7BA0544FA6B}.TIFF for claim 333333333 didn't work; was it restricted? false; and type 10
got error (soap:Server) The requested item was not found. Object identity: classId=Document&objectId={CE7EA941-7CB8-4627-8788-E7BA0544FA6B}&objectStore={E4765662-D249-4827-BF8A-9AFB972EAE8D}.  Class name: Document.
```
Is the only one that failed to fetch after being listed by ListDocuments.
So... it works as far as I can tell but given the limited range of test data it's still a crapshoot.
